url: https://dcleres.github.io
baseurl: /investing_for_social_good/

# Site settings
title: EPFL - ADA - Fall 2018
email: david.cleres@epfl.ch
description: "Society is demanding that companies, both public and private, serve a social purpose. To prosper over time,
every company must not only deliver financial performance but also show how it makes a positive contribution to society. \n
- Laurence D. Fink, CEO BlackRock"


# Team names, titles and social links
people:
- name: David Cleres
  pic: DC
  position: Computationnal Science & Engineering (CSE)
  social:
    - title: twitter
      url: https://twitter.com/DavidCleres
    - title: facebook
      url: https://www.facebook.com/david.cleres
    - title: stack-overflow
      url: https://stackoverflow.com/users/9543860/dcleres

- name: Mike Jiao
  pic: 2
  position: Computer Science (CS)
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Nicolas Lesimple
  pic: 3
  position: Computationnal Science & Engineering (CSE)
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: EPFL
  - line: Lausanne

# Build settings
markdown: kramdown
permalink: pretty
